- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure subscription 1(ff0505e9-c1a9-47e2-8954-432c27ffad1e)'
    azureContainerRegistry: '{"loginServer":"dockerdemocontainerregistry2.azurecr.io", "id" : "/subscriptions/ff0505e9-c1a9-47e2-8954-432c27ffad1e/resourceGroups/ContainerRegistryResourceGroup/providers/Microsoft.ContainerRegistry/registries/DockerDemoContainerRegistry2"}'
    dockerComposeFile: '**/docker-compose-pipeline.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'
    arguments: '--build --abort-on-container-exit'