version: "3"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - external
      - internal

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - "5900:5900"
    networks:
      - internal

  demo-tests:
    build: .
    depends_on:
      - selenium-hub
      - chrome
    environment:
      - SELENIUM_GRID_URL=selenium-hub:4444/wd/hub
    networks:
      - external
networks:
  external:
    driver: bridge
  internal:
    driver: bridge